name: Build & Deploy Next.js (standalone) to Azure App Service

on:
  push: { branches: [ master ] }
  workflow_dispatch:

# 동시에 여러 배포가 겹치지 않도록 (권장)
concurrency:
  group: mydea-frontend-prod
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build (standalone)
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      # ── 강제 검증: standalone 산출물 없으면 실패 ─────────────────────────────
      - name: Assert standalone output exists
        run: |
          echo "== .next layout =="
          ls -al .next || true
          if [ ! -d ".next/standalone" ]; then
            echo "❌ .next/standalone not found (standalone 빌드가 안 나왔어요)"
            exit 1
          fi
          test -f .next/standalone/server.js
          test -d .next/static

      # ── 패키징: ZIP 최상단이 server.js / node_modules 가 되도록 ─────────────
      - name: Package standalone output
        run: |
          rm -rf package && mkdir -p package
          cp -r .next/standalone/* package/
          mkdir -p package/.next/static
          cp -r .next/static/* package/.next/static/
          if [ -d public ]; then mkdir -p package/public && cp -r public/* package/public/; fi
          echo "== packaged root =="
          ls -al package | sed -n '1,120p'
          test -f package/server.js && test -d package/node_modules && test -d package/.next/static

      - name: Create release.zip
        run: |
          (cd package && zip -r ../release.zip .)
          echo "== zip top =="
          unzip -l release.zip | sed -n '1,60p'

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release
          path: .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DCC3CFFF754D40EC91632123281E68C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF2F17DEA22049598F871624F2C13252 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_40ED88AB27D24EB795F402493C787FE4 }}

      - name: Deploy (Run-From-Package)
        uses: azure/webapps-deploy@v3
        with:
          app-name: mydea-frontend
          package: release.zip      # ← 반드시 zip 파일
          type: zip
