name: Build and deploy Node.js app to Azure Web App - mydea-frontend

on:
  push: { branches: [ master ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      # (선택) CI에서도 한 번 빌드 점검만 해보고 싶다면 주석 해제
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '20.x'
      #     cache: 'npm'
      #     cache-dependency-path: 'package-lock.json'
      # - run: npm ci
      # - run: npm run build

      # ✅ 서버 빌드용 "소스만" 아티팩트 업로드
      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-src
          path: |
            app
            pages
            public
            src
            package.json
            package-lock.json
            next.config.* 
            tsconfig.json

      - name: Download source artifact
        uses: actions/download-artifact@v4
        with:
          name: node-src
          path: dist

      - name: Archive source (release.zip)
        run: |
          cd dist
          zip -r ../release.zip . -q
          cd ..
          unzip -l release.zip | sed -n '1,120p'

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DCC3CFFF754D40EC91632123281E68C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF2F17DEA22049598F871624F2C13252 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_40ED88AB27D24EB795F402493C787FE4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mydea-frontend'
          slot-name: 'Production'
          package: 'release.zip'
