name: Build & Deploy Next.js (standalone) to Azure App Service

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: mydea-frontend-prod
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build (standalone)
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Assert standalone output exists
        run: |
          ls -al .next
          if [ ! -d ".next/standalone" ]; then
            echo "❌ .next/standalone not found"
            exit 1
          fi
          test -f .next/standalone/server.js

      - name: Package standalone output
        run: |
          set -e
          rm -rf package && mkdir -p package

          # 1) standalone 산출물 복사 (server.js, node_modules 등)
          cp -r .next/standalone/* package/

          # 2) 정적 파일(static) + BUILD_ID
          mkdir -p package/.next/static
          cp -r .next/static/* package/.next/static/
          mkdir -p package/.next
          cp .next/BUILD_ID package/.next/BUILD_ID

          # 3) ✅ 서버 런타임이 참조하는 server/ 트리 추가
          if [ -d ".next/server" ]; then
            mkdir -p package/.next/server
            cp -r .next/server/* package/.next/server/
          fi

          # 4) 루트 manifest 몇 개도 복사
          for f in \
            app-build-manifest.json \
