name: Build and deploy Node.js app to Azure Web App - mydea-frontend

on:
  push: { branches: [ master ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify outputs
        run: |
          test -d .next || (echo "❌ .next missing"; exit 1)
          test -f node_modules/.bin/next || (echo "❌ next binary missing"; ls -al node_modules/.bin; exit 1)
          du -sh .next node_modules || true

      # (선택) devDependencies 제거로 용량 축소 — next는 dependencies에 있으니 안전
      # - name: Prune dev deps
      #   run: npm prune --omit=dev

      - name: Create release.zip at repo root
        run: |
          zip -r release.zip \
            .next \
            node_modules \
            public \
            package.json \
            package-lock.json \
            next.config.* \
            -q
          unzip -l release.zip | sed -n '1,200p'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release
          path: .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DCC3CFFF754D40EC91632123281E68C9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF2F17DEA22049598F871624F2C13252 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_40ED88AB27D24EB795F402493C787FE4 }}

      # - name: Warm restart
      #   run: az webapp restart --name mydea-frontend --resource-group <YOUR_RG>

      - name: Deploy to Azure Web App (Run-From-Package)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mydea-frontend'
          slot-name: 'Production'
          package: 'release.zip'
          type: 'zip'
          clean: true
          restart: true
